### ISSUE TITLE
Error in the code execution

### ISSUE THREAD

**Issue by kumarballapavan** [bghojogh/Haze-Removal-Dark-Channel-Prior#1]
I am getting the following error, I request you to kindly help me to resolve the issue.

FileNotFoundError: [Errno 2] No such file or directory: './intermediate_saved_files/rain_detection/saved_train_files/lda.pkl'

**Comment by bghojogh** [comment]
> I am getting the following error, I request you to kindly help me to resolve the issue.
> 
> FileNotFoundError: [Errno 2] No such file or directory: './intermediate_saved_files/rain_detection/saved_train_files/lda.pkl'

This project was for a vehicle project. In a part of this project, I implemented the dark channel prior method. If you run the whole project, you should put some images in the directory './input_images/'. Then, the function "weather_module()" in main.py tries to detect the levels of haze, light (luminance), and rain in the image. If haze removal is required, it calls the function "Remove_Haze()" in main.py. In that function, we instantiate the class "HazeRemoval" which is the implementation of dark channel prior method for haze removal. If you want to just use the module "HazeRemoval", you can slightly edit the function "Remove_Haze()" in main.py as desired and input the image(s) to that function directly.
